### ISSUE TITLE
주변기기 검색해서 출력해주는 함수 권한 체크 오류

### ISSUE THREAD

**Issue by coyadon** [noodles8436/OSS-Buddy#14]
**오류 발생 코드 기재**
> 
'checkSelfPermission(android.content.Context, java.lang.String)' in 'android.support.v4.content.ContextCompat' cannot be applied to '(anonymous android.content.BroadcastReceiver, java.lang.String)'
**오류 발생 소스 기재**
private final BroadcastReceiver receiver = new BroadcastReceiver() {
        public void onReceive(Context context, Intent intent) {
            String action = intent.getAction();
            if (BluetoothDevice.ACTION_FOUND.equals(action)) {
                // Discovery has found a device. Get the BluetoothDevice
                // object and its info from the Intent.
                BluetoothDevice device = intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);
                if (ActivityCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH_CONNECT) != PackageManager.PERMISSION_GRANTED) {
                    // TODO: Consider calling
                    //    ActivityCompat#requestPermissions
                    // here to request the missing permissions, and then overriding
                    //   public void onRequestPermissionsResult(int requestCode, String[] permissions,
                    //                                          int[] grantResults)
                    // to handle the case where the user grants the permission. See the documentation
                    // for ActivityCompat#requestPermissions for more details.
                    return;
                }
                String deviceName = device.getName();
                String deviceHardwareAddress = device.getAddress(); // MAC address
                btArrayAdapter.add(deviceName);
                deviceAddressArray.add(deviceHardwareAddress);
                btArrayAdapter.notifyDataSetChanged();
            }
        }
    };
-- if (ActivityCompat.checkSelfPermission(this, Manifest.permission.BLUETOOTH_CONNECT) != PackageManager.PERMISSION_GRANTED)에서 this에 빨간 줄

**해당 오류가 발생하기까지의 상황**
페어링되었던 기기들은 모두 나오도록 했지만 자동 페어링을 하기 위해서는 주변 기기들을 검색하는 기능이 필요한데 함수들을 모두 입력했을 때 권한 체크를 하라는 오류가 나와서 이를 추가하였더니 오류가 발생했다.

**바람직한 결과값**
소스의 의도한 결과를 적어주세요. ( 오류가 발생하지 않았다면 )
주변에 검색할 수 있는 기기들이 나타난다.
**스크린샷**

**[OPTION] 추가적인 코멘트를 적어주세요**

**Comment by noodles8436** [comment]
블루투스 기능을 사용하지 않는 것으로 확정한 것으로 기억합니다.
맞다면 이 Issue를 Close해주세요. @coyadon

**Comment by coyadon** [comment]
블루투스 기능을 사용하지 않고 gps를 사용하기로 하였습니다.
