### ISSUE TITLE
GPS 주소 수집 및 전달

### ISSUE THREAD

**Issue by jooyoung39** [noodles8436/OSS-Buddy#15]
**이 프로젝트에 필요한 기능은 무엇인가요?**

현재 사용자의 GPS 주소를 수집하고 서버에 전달할 수 있어야 한다.

**해당 기능이 필요한 이유가 무엇인가요?**

사용자의 위치를 확인하여 어느 버스 정류장에서 버스 예약을 진행하는 것인지 확인하는 과정이 필요하다. 

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**

안드로이드 스튜디오 프로그래밍을 통해 해당 GPS를 받아와야 한다.
수집한 GPS 주소를 서버에 전달하는 과정을 프로그래밍 한다.

**[OPTION] 추가적인 코멘트를 적어주세요**

블루투스 자동 페어링 과정에서 문제점을 발견하여 GPS를 활용하도록 계획이 변경되었다.

**Comment by coyadon** [comment]
GPS 정보 (위도와 경도) 코드 작성이 완료되었습니다.

**Comment by coyadon** [comment]
서버에 전달 하는 부분을 구현하면 됩니다.

**Comment by noodles8436** [comment]
서버측 GPS 처리 구현하였습니다.
추후 Java API를 제공해드릴 예정입니다.

**Comment by noodles8436** [comment]
정상적으로 문제가 해결되었습니다.
