### ISSUE TITLE
추후 brach merge를 위해, android branch의 main, bluetooth 폴더를 android  폴더에 담아주세요.

### ISSUE THREAD

**Issue by noodles8436** [noodles8436/OSS-Buddy#17]
**이 프로젝트에 필요한 기능은 무엇인가요?**
추후 github branch merge를 위한 폴더 정리

**해당 기능이 필요한 이유가 무엇인가요?**
merge 이후의 폴더 구조를 android, raspberry, server 로 구성하기 위해서 입니다.

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**
branch 내부 폴더 구성을 변경해주세요.

**[OPTION] 추가적인 코멘트를 적어주세요**

**Comment by coyadon** [comment]
완료하였습니다.
