### ISSUE TITLE
버스기사전용 애플리케이션에서 서버로부터 버스 예약 현황을 수집하는 기능 구현

### ISSUE THREAD

**Issue by jooyoung39** [noodles8436/OSS-Buddy#18]
**이 프로젝트에 필요한 기능은 무엇인가요?**

해당 버스 예약 현황 및 알림
대기해야 하는 버스 정류장 정보

**해당 기능이 필요한 이유가 무엇인가요?**

해당 버스의 예약자가 있음을 알리기 위함이다.
어느 버스 정류장에서 예약자가 기다리는지 알기 위함이다.

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**

안드로이드 스튜디오와 서버로의 연동 등.

**[OPTION] 추가적인 코멘트를 적어주세요**

**Comment by noodles8436** [comment]
해당 부분은 서버측에서 아직 구현중에 있습니다.
9월 7일 내로 서버측 구현후, JAVA 기반 API를 최대한 빠르게 제공할 테니, 해당 API를 사용하면 될 것 같습니다.

**Comment by coyadon** [comment]
완료하였습니다.
