### ISSUE TITLE
버스 예약을 위한 버스 정보 수집

### ISSUE THREAD

**Issue by jooyoung39** [noodles8436/OSS-Buddy#20]
**이 프로젝트에 필요한 기능은 무엇인가요?**

서버에서 버스의 대수 및 번호를 받아와야 한다.

**해당 기능이 필요한 이유가 무엇인가요?**

사용자가 원하는 버스를 예약하기 위함이다.

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**

현재 구현된 더블 클릭 기능에 임의적으로 적용된 버스 대수 및 번호를 서버에서 받아오는 값으로 적용해야 한다.

**[OPTION] 추가적인 코멘트를 적어주세요**

추후 서버와 연결된 이후에 적용하려 합니다.

**Comment by noodles8436** [comment]
안드로이드측에서 서버측에 접근중인 버스 목록 조회를 요청할 경우
routeNo, arrivalNodeLeft, vehicleNo 로 구성된 List 데이터가 전송됩니다.
이는 추후에 Java API로 제공해드릴 예정입니다
