### ISSUE TITLE
애플리케이션에서 사용자의 블루투스 주소와 전화번호 수집

### ISSUE THREAD

**Issue by jooyoung39** [noodles8436/OSS-Buddy#7]
**이 프로젝트에 필요한 기능은 무엇인가요?**
애플리케이션에서 사용자의 블루투스 주소를 수집한다.
애플리케이션에서 사용자의 전화번호를 수집한다.

**해당 기능이 필요한 이유가 무엇인가요?**
사용자를 식별하기 위함이다.

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**
안드로이드 코드 구현 등

**Comment by noodles8436** [comment]
사용자의 블루투스 주소는 더이상 필요로 하지 않습니다.
