### ISSUE TITLE
버스기사 애플리케이션 구현

### ISSUE THREAD

**Issue by jooyoung39** [noodles8436/OSS-Buddy#8]
**이 프로젝트에 필요한 기능은 무엇인가요?**
애플리케이션 회원가입 기능을 구현하면서 버스기사가 운행하는 버스의 번호를 수집한다.
회원가입 기능 구현 후, 로그인 기능을 구현한다.
버스기사가 해당 버스 정류장에서 탑승자가 기다리고 있음을 알 수 있도록 한다. (예약 알림)

**해당 기능이 필요한 이유가 무엇인가요?**
몇 번 버스를 운행하는 버스기사인지 알 수 있도록 한다.
버스기사 전용 애플리케이션을 구현하여 버스기사가 애플리케이션을 통해 탑승자의 위치(버스 정류장)을 알 수 있도록 한다.

**해당 기능을 구현하기 위해 필요한 것들은 무엇인가요?**
안드로이드 스튜디오를 통한 프로그래밍 등.

**Comment by coyadon** [comment]
현재 본인이 운전하는 차량의 번호를 입력하는 것까지 구현하였습니다.
(아,바,사,자)가 들어가는 지, 빈칸을 제거하고 반환하는지, 공백입력했을 때 오류 메세지 띄우기 등
